# An example recipe that shows the creation of a user role.
name: 'Wunder base'
description: "Enable base themes and configuration. Meant as a lighter base than the default installation profile"
type: 'Setup'
install:
  - breakpoint
  - claro
  - wunder_claro
  - help
  - toolbar
  - taxonomy
  - menu_link_content
  - menu_ui
  - options
  - path
  - path_alias
  - taxonomy
  - token
  - action
  - automated_cron
  - ckeditor5
  - config
  - field_ui
  - editor
  - views_ui
  - views
  - simplei
  - datetime
  - image
  - link
  - jsonapi
  - datetime_range
  - metatag
  - webform
  - webform_ui
  - admin_toolbar
  - menu_link_attributes

config:
  import:
    action: '*'
    ckeditor5: '*'
    taxonomy: '*'
    claro: '*'
    webform: '*'
    webform_ui: '*'
    editor: '*'
  actions:
    system.theme:
      simple_config_update:
        default: 'wunder_claro'

